/*
 * Copyright © 2020 Cask Data, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

CONNECT CDAP@ORCL;

INSERT INTO CDAP.EMPLOYEES2 (EMPNO, DEPT, MGR, MGR_DEPT, ENAME, LVL)
VALUES (7839,'A',NULL,NULL,'KING',1);

INSERT INTO CDAP.EMPLOYEES2 (EMPNO, DEPT, MGR, MGR_DEPT, ENAME, LVL)
VALUES (7566,'B',7839,'A','JONES',2);

INSERT INTO CDAP.EMPLOYEES2 (EMPNO, DEPT, MGR, MGR_DEPT, ENAME, LVL)
VALUES (7788,'B',7566,'B','SCOTT',3);

INSERT INTO CDAP.EMPLOYEES2 (EMPNO, DEPT, MGR, MGR_DEPT, ENAME, LVL)
VALUES (7876,'D',7788,'B','ADAMS',4);

INSERT INTO CDAP.EMPLOYEES2 (EMPNO, DEPT, MGR, MGR_DEPT, ENAME, LVL)
VALUES (7902,'C',7566,'B','FORD',3);

INSERT INTO CDAP.EMPLOYEES2 (EMPNO, DEPT, MGR, MGR_DEPT, ENAME, LVL)
VALUES (7369,'D',7902,'C','SMITH',4);

INSERT INTO CDAP.EMPLOYEES2 (EMPNO, DEPT, MGR, MGR_DEPT, ENAME, LVL)
VALUES (7698,'C',7839,'A','BLAKE',2);

INSERT INTO CDAP.EMPLOYEES2 (EMPNO, DEPT, MGR, MGR_DEPT, ENAME, LVL)
VALUES (7499,'C',7698,'C','ALLEN',3);

INSERT INTO CDAP.EMPLOYEES2 (EMPNO, DEPT, MGR, MGR_DEPT, ENAME, LVL)
VALUES (7521,'C',7698,'C','WARD',3);

INSERT INTO CDAP.EMPLOYEES2 (EMPNO, DEPT, MGR, MGR_DEPT, ENAME, LVL)
VALUES (7654,'C',7698,'C','MARTIN',3);

INSERT INTO CDAP.EMPLOYEES2 (EMPNO, DEPT, MGR, MGR_DEPT, ENAME, LVL)
VALUES (7844,'C',7698,'C','TURNER',3);

INSERT INTO CDAP.EMPLOYEES2 (EMPNO, DEPT, MGR, MGR_DEPT, ENAME, LVL)
VALUES (7900,'C',7698,'C','JAMES',3);

INSERT INTO CDAP.EMPLOYEES2 (EMPNO, DEPT, MGR, MGR_DEPT, ENAME, LVL)
VALUES (7782,'C',7839,'A','CLARK',2);

INSERT INTO CDAP.EMPLOYEES2 (EMPNO, DEPT, MGR, MGR_DEPT, ENAME, LVL)
VALUES (7934,'E',7782,'C','MILLER',3);

COMMIT;
